# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import hello_pb2 as hello__pb2


class BasicServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BasicFunction = channel.unary_unary(
                '/BasicService/BasicFunction',
                request_serializer=hello__pb2.BasicRequest.SerializeToString,
                response_deserializer=hello__pb2.BasicResponse.FromString,
                )


class BasicServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BasicFunction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BasicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BasicFunction': grpc.unary_unary_rpc_method_handler(
                    servicer.BasicFunction,
                    request_deserializer=hello__pb2.BasicRequest.FromString,
                    response_serializer=hello__pb2.BasicResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BasicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BasicService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BasicFunction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BasicService/BasicFunction',
            hello__pb2.BasicRequest.SerializeToString,
            hello__pb2.BasicResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
