# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bhello.proto\"\x1f\n\x0c\x42\x61sicRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\"!\n\rBasicResponse\x12\x10\n\x08response\x18\x01 \x01(\t2@\n\x0c\x42\x61sicService\x12\x30\n\rBasicFunction\x12\r.BasicRequest\x1a\x0e.BasicResponse\"\x00\x62\x06proto3'
)




_BASICREQUEST = _descriptor.Descriptor(
  name='BasicRequest',
  full_name='BasicRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='BasicRequest.request', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=46,
)


_BASICRESPONSE = _descriptor.Descriptor(
  name='BasicResponse',
  full_name='BasicResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='BasicResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['BasicRequest'] = _BASICREQUEST
DESCRIPTOR.message_types_by_name['BasicResponse'] = _BASICRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BasicRequest = _reflection.GeneratedProtocolMessageType('BasicRequest', (_message.Message,), {
  'DESCRIPTOR' : _BASICREQUEST,
  '__module__' : 'hello_pb2'
  # @@protoc_insertion_point(class_scope:BasicRequest)
  })
_sym_db.RegisterMessage(BasicRequest)

BasicResponse = _reflection.GeneratedProtocolMessageType('BasicResponse', (_message.Message,), {
  'DESCRIPTOR' : _BASICRESPONSE,
  '__module__' : 'hello_pb2'
  # @@protoc_insertion_point(class_scope:BasicResponse)
  })
_sym_db.RegisterMessage(BasicResponse)



_BASICSERVICE = _descriptor.ServiceDescriptor(
  name='BasicService',
  full_name='BasicService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=83,
  serialized_end=147,
  methods=[
  _descriptor.MethodDescriptor(
    name='BasicFunction',
    full_name='BasicService.BasicFunction',
    index=0,
    containing_service=None,
    input_type=_BASICREQUEST,
    output_type=_BASICRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BASICSERVICE)

DESCRIPTOR.services_by_name['BasicService'] = _BASICSERVICE

# @@protoc_insertion_point(module_scope)
